spring:
  application:
    name: book-management-system
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/book-management-system
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    out-of-order: true

springdoc:
  swagger-ui:
    operations-sorter: method
